// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHgeCbEpfeVfj-iPAc6UMRNY9iW-rHQ0A',
    appId: '1:497532705020:web:455fe233ddaf85c605df79',
    messagingSenderId: '497532705020',
    projectId: 'team-chat-58b6f',
    authDomain: 'team-chat-58b6f.firebaseapp.com',
    storageBucket: 'team-chat-58b6f.appspot.com',
    measurementId: 'G-CECTKFW68Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnbLYar6RlNyKRZuNWWvS7JaAcXJCvkQ',
    appId: '1:497532705020:android:62788eddf1c2011505df79',
    messagingSenderId: '497532705020',
    projectId: 'team-chat-58b6f',
    storageBucket: 'team-chat-58b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCD9UyCcZ5_1RLvvWxdSO_r7TzxFQzS_0',
    appId: '1:497532705020:ios:14821eff65f3a27905df79',
    messagingSenderId: '497532705020',
    projectId: 'team-chat-58b6f',
    storageBucket: 'team-chat-58b6f.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCD9UyCcZ5_1RLvvWxdSO_r7TzxFQzS_0',
    appId: '1:497532705020:ios:2a4462578c48742805df79',
    messagingSenderId: '497532705020',
    projectId: 'team-chat-58b6f',
    storageBucket: 'team-chat-58b6f.appspot.com',
    iosBundleId: 'com.example.client.RunnerTests',
  );
}
